services:
  postgres:
    image: postgres:15-alpine
    command:
      ["postgres","-c","fsync=off","-c","synchronous_commit=off","-c","full_page_writes=off"]
    ports:
      - "127.0.0.1:5442:5432"
    environment:
      POSTGRES_USER: dbtest
      POSTGRES_PASSWORD: dbtest
      DB_NAME: dbtest
